environment:
  nodejs_version: "4"
install:
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version
  - npm install
  - npm run webdriver
  - SYSTEMINFO
test_script:
  - node --version
  - npm --version
  - npm test
build: off
